language: cpp

os:
- linux
- osx
- windows

dist: trusty

addons:
  apt:
    packages:
    - libudev-dev

env:
  global:
  - PREBUILD_TARGETS="6.0.0 8.0.0 10.0.0 11.0.0 12.0.0"
  - PREBUILD_ELECTRON_TARGETS="3.0.0 4.0.0 4.0.4 5.0.0 6.0.0"
  matrix:
  - ARCH="x64"
  - ARCH="ia32"

matrix:
  exclude:
  - os: linux
    env: ARCH="ia32"
  - os: osx
    env: ARCH="ia32"

before_install:
- |
  if [ $TRAVIS_OS_NAME == windows ]; then
    choco install nodejs-lts
    export PATH="/c/Program Files/nodejs:$PATH"
    export GYP_MSVS_VERSION=2015
  fi
- $CXX --version
- node --version
- npm --version

install:
- npm install

script:
- |
  for target in $PREBUILD_TARGETS; do
    npm run prebuild -- -t $target --arch=$ARCH
  done

  for target in $PREBUILD_ELECTRON_TARGETS; do
    npm run prebuild -- -t $target --arch=$ARCH -r electron
  done
deploy:
  provider: releases
  api_key:
    # tm-rampart personal access token
    secure: $prebuild_upload
  file_glob: true
  file: prebuilds/*
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
