language: cpp

os:
- linux
- osx
- windows

addons:
  apt:
    packages:
    - libudev-dev

env:
  matrix:
  - ARCH="x64"
  - ARCH="ia32"

matrix:
  exclude:
  - os: linux
    env: ARCH="ia32"
  - os: osx
    env: ARCH="ia32"

before_install:
- |
  if [ $TRAVIS_OS_NAME == windows ]; then
    choco install nodejs-lts
    export PATH="/c/Program Files/nodejs:$PATH"
    export GYP_MSVS_VERSION=2015
  fi
- $CXX --version
- node --version
- npm --version

install:
- npm install

script:
  - PUBLISH_BINARY=false
  # if we are building a tag then publish
  - if [[ $TRAVIS_BRANCH == `git describe --tags --always HEAD` ]]; then PUBLISH_BINARY=true; fi;
  - >
    if [ "$PUBLISH_BINARY" == true ]; then
      npm install -g prebuild
      npm run prebuild -- -t 11.15.0 -t 12.7.0 -t 13.0.0 -t 14.0.0 -r node --arch=$ARCH --upload $prebuild_upload
      npm run prebuild -- -t 8.0.0 -t 9.0.0 -t 10.0.0 -t 11.0.0-beta.1 -r electron --arch=$ARCH --upload $prebuild_upload
    fi
