language: cpp

os:
- linux
- osx
- windows

dist: trusty

addons:
  apt:
    packages:
    - libudev-dev

env:
  matrix:
  - ARCH="x64"
  - ARCH="ia32"

matrix:
  exclude:
  - os: linux
    env: ARCH="ia32"
  - os: osx
    env: ARCH="ia32"

before_install:
- |
  if [ $TRAVIS_OS_NAME == windows ]; then
    choco install nodejs-lts
    export PATH="/c/Program Files/nodejs:$PATH"
    export GYP_MSVS_VERSION=2015
  fi
- $CXX --version
- node --version
- npm --version

install:
- npm install

script:
  - PUBLISH_BINARY=false
  # if we are building a tag then publish
  - if [[ $TRAVIS_BRANCH == `git describe --tags --always HEAD` ]]; then PUBLISH_BINARY=true; fi;
  - >
    if [ "$PUBLISH_BINARY" == true ]; then
      npm install -g prebuild
      npm run prebuild -- -t 6.14.4 -t 8.12.0 -t 9.11.2 -t 10.16.1 -t 11.15.0 -t 12.7.0 -r node --upload $prebuild_upload
      npm run prebuild -- -t 2.0.0 -t 3.0.0 -t 4.0.4 -t 5.0.0 -t 6.0.0 -r electron --upload $prebuild_upload
    fi
